### PR TITLE
First steps

### PR DESCRIPTION
**Pull request by eriknewland**
https://nostrkit-eight.vercel.app/

Added skeleton of NOSTR Kit Logic.

1. Generate npub/nsec via nostr-tools npm package
2. Generate nip-05 and write result to /.well-known/nostr.json
3. Generate lightning address via lnbits (NOSTR Kit master wallet, programmatically create a user, wallet, lnurlP and retrieve the lightning address)

### CODE REVIEW

**Comment by bitkarrot** [comment]
Lets discuss UX/UI over chat and work through that. Thanks for initial skeleton

**Review by bitkarrot — CHANGES_REQUESTED** [review]
as we discussed on the call 10 aug, to do a simple 1 page form with links to instructions and also a link to modal(?) npub generator, and a manage section people can login to with a magic link sent to their DM. If you don't have time to do a directory, see if Tony can help with that, it might be a useful guide and faster to look up existing entries.  parsing the JSON visually can get exhausting as the file grows larger.

**Comment by bitkarrot** [comment]
@amsalmeron pls see comments above and work together w/Erik, thanks :)

**Comment by eriknewland** [comment]
> as we discussed on the call 10 aug, to do a simple 1 page form with links to instructions and also a link to modal(?) npub generator, and a manage section people can login to with a magic link sent to their DM. If you don't have time to do a directory, see if Tony can help with that, it might be a useful guide and faster to look up existing entries. parsing the JSON visually can get exhausting as the file grows larger.

Still need to handle the magic link login, perhaps we can discuss that tonight.


also realized today that vercel doesnt really support filesystem reads/writes (as its serverless computing)...any ideas on deployment? I need to do some research but i think i have better filesystem control with digital ocean

Quick video reference:

https://www.loom.com/share/7a49539bfb85472abf28d0f65ef009a8?sid=68320c40-6df3-4479-b22c-d5641d2702a8

Sadly the sats.lnaddy server stopped working a few minutes before I was able to push/wrap everything up, but it was working fine this morning.

**Pull request closed without merging**
